### ISSUE TITLE
Input ཅེན་ཕོ་ stays as is

### ISSUE THREAD

**Issue by heacu** [tibetan-nlp/old-tibetan-corpus#10]
As in the title, we expect ཅེན་ཕོ་ > ཆེན་པོ་, but the current version of the grammar does not make the conversion.

**Comment by FChrispz** [comment]
@heacu the rule 

SUBSTITUTE ("(ཅེ|ཆེ)(ད|ན)་"r) ("ཆེན་") TARGET (σ) (1 ("((པོ|ཕོ)(འི|ར|ས)?(་?))"r));

will take care of it.
