### ISSUE TITLE
Replace [] with [---] or something more informative in OT Chronicle CONLLU

### ISSUE THREAD

**Issue by heacu** [tibetan-nlp/old-tibetan-corpus#12]
Particularly on pages 27 and 28 of the OT Chronicle, what was converted to Unicode as `[---]` is showing up in BRAT and our CONLLU as `[]`. These are important indicators, since they convey that the (partial) words on either side are not directly adjacent to each other; the source text has a gap.

I prefer `[---]` to `[]`, but am also open to alternatives @FChrispz

**Comment by FChrispz** [comment]
@heacu I replaced [] with [---]
